baseURL = "https://Tobiuo1022.github.io/Tobiuo-Blog/"
languageCode = "ja"
title = "Tobiuo Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  ShowToc = true

[params.homeInfoParams]
  Title = "Tobiuo Blog"
  Content = "ゲームや日常についてゆるく書いてます。"

[menu]
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 10
